### ISSUE TITLE
Mac Controller Errors

### ISSUE THREAD

**Issue by kyatt** [larsiusprime/SteamWrap#18]
When building Steamwrap on my Mac, I get these 3 warnings that turn into errors when compiling my HaxeFlixel application later:

```
Link: ../ndll/Mac64/steamwrap.ndll
../steamwrap/api/Controller.hx:389: characters 2-28 : cpp.Function<Int -> Int -> Int -> cpp.Void, cpp.abi.Abi> cannot be called
../steamwrap/api/Controller.hx:404: characters 2-23 : cpp.Function<Int -> Int -> Int -> Int -> Int -> cpp.Void, cpp.abi.Abi> cannot be called
../steamwrap/api/Controller.hx:409: characters 2-23 : cpp.Function<Int -> Int -> Int -> Int -> Int -> cpp.Void, cpp.abi.Abi> cannot be called
```
They correspond to the methods SteamWrap_TriggerVibration (389) and SteamWrap_SetLEDColor (404 and 409). Also, I get these errors when using the Mac64 Steamwrap.ndll that comes with the master branch download.

**Comment by larsiusprime** [comment]
Do you get these errors on PC as well?

**Comment by larsiusprime** [comment]
Also, what version of the Steamworks SDK are you using?

**Comment by kyatt** [comment]
I've only been getting them on Mac. I'm using the most recent Steamworks SDK, version 1.41.

Also, the errors don't show up on PC.

**Comment by larsiusprime** [comment]
Okay, that helps narrow things down a lot. Sorry this is taking a while.

**Comment by larsiusprime** [comment]
I believe I've fixed these now,.
